
project_id = "lckyfjxdnmwhmruvgpwn"

[api]
enabled = true
url = "https://lckyfjxdnmwhmruvgpwn.supabase.co"

[functions]
[functions.analyze-resume]
[functions.fetch-jobs]
[functions.fetch-jobs-multi]
