
project_id = 'lckyfjxdnmwhmruvgpwn'

[functions.import-jobspy-jobs]
verify_jwt = true

[functions.scheduled-job-import]
verify_jwt = true

[functions.analyze-resume]
verify_jwt = false

[functions.jobspy-bridge]
verify_jwt = true

[functions.setup-jobspy-cron]
verify_jwt = true
